repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: 'rerun_animation/.*'
        args: [--check-only, --profile, black]
      - id: isort
        files: 'scripts/.*'
        args: [--check-only, --profile, black]
      - id: isort
        files: 'setup.py'
        args: [--check-only, --profile, black]      
      
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: [--check]