# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

# theme = "congo"

baseURL = "https://moverseai.github.io/rerun-animation"
defaultContentLanguage = "en"
# relativeURLs = true

enableRobotsTXT = true
paginate = 10
summaryLength = 0

autoSwitchAppearance = false
defaultAppearance = "light"

enableSearch = true
enableCodeCopy = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[header]
  layout = "hamburger"
  logo = "img/logo-32.png"
  logoDark = "img/logo-32.png"

[footer]
  showThemeAttribution = false


[article]
  showTableOfContents = true